-- GENERATED by tools/generate_slices.py -- do not edit by hand.

return {
	rank1 = {
		radius = 190,
		inner = 130.5,
		outer = 258,
		size = { 190, 140 },
		fill = "slice_rank1.png",
		line = "slice_rank1_line.png",
		highlight = "slice_rank1_highlight.png",
	},
	rank2 = {
		radius = 320,
		inner = 260.5,
		outer = 388,
		size = { 121, 140 },
		fill = "slice_rank2.png",
		line = "slice_rank2_line.png",
		highlight = "slice_rank2_highlight.png",
	},
	hub_category = {
		radius = 190,
		inner = 130.5,
		outer = 258,
		size = { 116, 140 },
		fill = "slice_hub_category.png",
		line = "slice_hub_category_line.png",
		highlight = "slice_hub_category_highlight.png",
	},
}
