"""Emit slice art for both wheel ranks plus the Lua geometry table that describes them.

Run this whenever L1_RADIUS / L2_RADIUS / L2_TIGHTEN change in modules/wheel.lua.
The generator is the single owner of the petal box sizes; slice_geometry.lua is
generated output, not hand-maintained.
"""
import math, os, re, sys
import png_io, generate

WHEEL_LUA = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         "..", "scripts", "mods", "Vox Semaphore",
                         "modules", "wheel.lua")


def wheel_constants(path):
    """Read the wheel's geometry constants from wheel.lua.

    wheel.lua is the single owner of the layout; mirroring these numbers here
    would be a silent divergence the first time anyone retunes the wheel.
    """
    src = open(path, encoding="utf-8").read()
    want = {"SLICE_SPACING": None, "L1_RADIUS": None,
            "L2_RADIUS": None, "L2_TIGHTEN": None, "HUB_ARC_SPACING": None}
    for name in want:
        m = re.search(r"^local\s+%s\s*=\s*([^\n]+?)\s*$" % name, src, re.M)
        if not m:
            raise SystemExit("could not find %s in %s" % (name, path))
        expr = m.group(1).rstrip(";")
        if not re.fullmatch(r"[-+*/(). 0-9]|[-+*/(). 0-9a-z_]*", expr):
            raise SystemExit("unexpected expression for %s: %r" % (name, expr))
        want[name] = float(eval(expr, {"__builtins__": {}}, {"math": math}))
    return want


_C = wheel_constants(WHEEL_LUA)
SLICE_SPACING = _C["SLICE_SPACING"]
L1_RADIUS, L2_RADIUS = _C["L1_RADIUS"], _C["L2_RADIUS"]
L2_TIGHTEN = _C["L2_TIGHTEN"]
HUB_ARC_SPACING = _C["HUB_ARC_SPACING"]
print("read from wheel.lua: spacing=%.5f L1=%g L2=%g tighten=%g"
      % (SLICE_SPACING, L1_RADIUS, L2_RADIUS, L2_TIGHTEN))

# --- measured from the vanilla 45-degree art ---------------------------------
V_HALF = 21.087
V_IN_OFF = L1_RADIUS - 130.5
V_OUT_OFF = 258.0 - L1_RADIUS
BOX_H = 140
INK_FRACTION = (2 * V_HALF) / math.degrees(SLICE_SPACING)

HERE = os.path.dirname(os.path.abspath(__file__))
DEST = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "assets")
GEO_DEST = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    HERE, "..", "scripts", "mods", "Vox Semaphore", "modules")
os.makedirs(DEST, exist_ok=True)

RANKS = (
    ("rank1", L1_RADIUS, SLICE_SPACING, 190),
    ("rank2", L2_RADIUS, SLICE_SPACING * (L1_RADIUS / L2_RADIUS) * L2_TIGHTEN, None),
    ("hub_category", L1_RADIUS, HUB_ARC_SPACING, None),
)

lua = [
    "-- GENERATED by tools/generate_slices.py -- do not edit by hand.",
    "",
    "return {",
]

for name, R, spacing, force_w in RANKS:
    half = math.degrees(spacing) * INK_FRACTION / 2.0
    r_in, r_out = R - V_IN_OFF, R + V_OUT_OFF
    box_w = force_w or (math.ceil(2 * r_out * math.sin(math.radians(half))) + 2)

    print("%s: slot %.3f deg, ink %.3f deg, band %.1f..%.1f, box %dx%d"
          % (name, math.degrees(spacing), half * 2, r_in, r_out, box_w, BOX_H))

    w, h, fill, line, high = generate.build(R, half, r_in, r_out, box_w, BOX_H)
    for suffix, buf in (("", fill), ("_line", line), ("_highlight", high)):
        fn = "slice_%s%s.png" % (name, suffix)
        png_io.write(os.path.join(DEST, fn), w, h, buf)
        print("   %-30s %dx%d  %d bytes" % (fn, w, h, os.path.getsize(os.path.join(DEST, fn))))

    lua.append("\t%s = {" % name)
    lua.append("\t\tradius = %g," % R)
    lua.append("\t\tinner = %g," % r_in)
    lua.append("\t\touter = %g," % r_out)
    lua.append("\t\tsize = { %d, %d }," % (box_w, BOX_H))
    lua.append("\t\tfill = \"slice_%s.png\"," % name)
    lua.append("\t\tline = \"slice_%s_line.png\"," % name)
    lua.append("\t\thighlight = \"slice_%s_highlight.png\"," % name)
    lua.append("\t},")

lua += ["}", ""]
geo = os.path.normpath(os.path.join(GEO_DEST, "slice_geometry.lua"))
open(geo, "w", newline="\n").write("\n".join(lua))
print("wrote %s" % geo)
